language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-3.2.2-20160721004418-4f94939.tar.gz | tar xz
- chmod ugo+x ci/*
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
- ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
- ci/ci-nonrelease.sh sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci core/publishLocal scalding/publishLocal tools/publishLocal
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci 'plugin/scripted'
- ci/sbt-ci-deploy.sh ivy http://commbank.artifactoryonline.com/commbank ext-releases-local-ivy plugin
after_script:
- rm -rf ci
env:
  global:
  - secure: Nytq9WalikIc2IrWZCAjfaEWA6YpE6zyJu3BIyOtTavO893b2pW00P7zqM14eZ/079TwgLRi91cEkmFdwceAggcy/yqA9dcyam29esO31Qh+TWUL1kF9EEnWMx6HBDLxq0NgKgsxAIcH1DbbtpnRQ2xCffmXA3Z8Mt1z5nzlKULHaKd5gMeT90BW/bxDbENsPKpgHri6rxiKYe12r0Ms+5ujtuC2hrLUAsdnb67lWuYWtcXYD+hpLzakXGX6hQiDUZjo75N8NnEVuji0vw3L1K1LLw1suyym4aIBPWDA130GTnnh1H63rr2VqFPDaCzx9TfudBRr1NZeJ/PEg24sffEykZebYSsmIfSM9DyEQQSAm6UwxrAknfhkSJ9uJ2I2PEUs8MWhM3vP9HXJDRVnxrafz/eKQ0o6PU2KtDA/3B2lXAPpromn+zUOWLsrRAyINOW7BmV3EBJ+qUiP+h7twphltk0zrocfyMUn/B6LOfQeVjw/iN9viXhvSDCqCUdNSFVThQST2K9fyQXJfPDB3D57zyuRL91dvOfCx9u68GbFjUWzIaZQsHGPlgWEIjj+Lhj5gvVELuYHmV340W46A/pHLhuqBqIXzlquzaniJdGx0dNUG4g5nHKdtPrFwAwlfGjfC7KKG4bcX8noDqrxzQKrMT4QPRY/LHtZdf+r5d0=
  - secure: DCSwHPNNXA2v8CNaX2nUaVdFrFeR64bx3VygiqKbrD/39Skvn21pj8TgKmvLo7TFR/vDBtSJqhHaXngyMrW0wK274OfDyZk+3G/atflk3j9CSkGEtZKV7jFYnVhBZtJeDUvYtEbfSABR3eo11oklOLbIJafqxjS7E5XNaoaZ6JlSChH0+rh0B4yYTLB3lHz+UCQALrHEAYoUfROzJWUXBHvixfzPSqcS8UEQg/n7fi1nGN0U/EKPzSQecozak5z+bSa+htTVXk4WsK0XEYuOlyxKOcq7RhKqjIYKExlTBo9OmimsxYGd8yPleoH/gUwy8KpUAQsZJm8amYwTn88bYqnOPNssyKwKFzO/BpGFEzVR60sTVE3GEDEuOzlMFw4HhbaT5yIRPetVHhyjpYzBDOicmS+n7tiTwxTOsCzSLtKe9eUjQhSknsiobcig4koP1pkI7Ie55b2B8p+nW9nIB0iZJKRFceDGNFwuttY0HVNsw5pwrf6/jschvL579KU/T796Mb9maOn/nfThSJ+OdimjjlEfE5E0fAq2tyDH2cONIdTbUNK2zgRudx2m/8NvHUr+ejqU0XE7Huinl+i+obqvgFmS5s28phGhyjnTvjUMyuFkfrCV1Wj4RcbKiNt6ubpJEOHtnAXdznOxqMOBE9ktAVRfMQjOG+mPzszNu7g=
